### ISSUE TITLE
数据增强后有许多图片是0字节

### ISSUE THREAD

**Issue by jplnasa5** [maozezhong/TIANCHI_XUELANG_AI_2#2]
/../../TIANCHI_XUELANG_AI_2/data/data_AugForTrain/defect_4文件夹里面的图片都是0字节
其它文件夹有正常的也有不正常的

**Comment by maozezhong** [comment]
你指的是自己重新运行数据增强后的脚本产生的图片是0字节的？还是我上传的分好类的图片是0字节的？
如果是我上传的那个图片文件有问题，你首先试一试重新增强看看是否有问题。如果重新增强产生的还是有问题，麻烦给个例子看看~

**Comment by jplnasa5** [comment]
后来发现是我电脑空间用完了，没问题。

但是我在ubuntu系统上运行出现另一个错误：
StopIteration: Invalid interpolation method antialias specified. Supported methods are nearest, bilinear, bicubic, hamming, box, lanczos
已经在/usr/local/lib/python3.6/site-packages/keras_preprocessing/image.py中添加了antialias还是报错不知什么原因。

**Comment by xincyu** [comment]
> 后来发现是我电脑空间用完了，没问题。
> 
> 但是我在ubuntu系统上运行出现另一个错误：
> StopIteration: Invalid interpolation method antialias specified. Supported methods are nearest, bilinear, bicubic, hamming, box, lanczos
> 已经在/usr/local/lib/python3.6/site-packages/keras_preprocessing/image.py中添加了antialias还是报错不知什么原因。

请问你解决了吗？我也遇到同样的问题。
